language: php

php:
  - 7.2

before_script:
  - npm install react-burger-menu
  - npm install --save redux-logger
  - cp .env.travis .env
  - rm phpunit.xml
  - cp .phpunit.xml.travis phpunit.xml
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed
  - php artisan passport:install  
  - php artisan key:generate

script:
- npm run production
- vendor/bin/phpunit
