
language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed
  - php artisan passport:install
  - php artisan key:generate

script:
  - npm install
  - npm run production
  - ./vendor/bin/phpunit
