version: '2'

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    ports:
      - 8080:80
    
  app:
    image: uracreative/identihub
    links:
      - db:mysql
    env_file: .env.docker
    volumes:
      - .:/var/www/app
      - /var/www/app/vendor
      #   - ./srv/invoiceninja/storage:/var/www/app/storage:rw
      #   - ./srv/invoiceninja/logo:/var/www/app/public/logo:rw
    restart: always
    
  db:
    image: mysql
    env_file: .env.docker
    restart: always
    volumes:
      - data-volume:/var/lib/mysql



volumes:
  data-volume:
      
